#!/bin/bash (only for syntax highlighting)
#
# functions for modular use by scripts
#

check_args() {
    if [ $# -lt 1 ]; then
        echo "error: config file missing"
        echo "usage: $0 <config-file>"
        exit 1
    fi
    if [ ! -f "$1" ]; then
        echo "error: file not found: $1"
        exit 1
    fi
    # import settings
    . "$1"
}

check_exit() {
    # $1: exit code, $?
    if [ $1 -ne 0 ]; then
        echo "oops, something went wrong, exiting."
        exit 1
    else
        echo -e "done.\n"
    fi
}

copy_files() {
    # copy files from server using rsync
    # rsync opts
    # -r recursive
    # -l copy symlinks as symlinks
    # -p preserve permissions
    # --chown set user/group
    # --owner --group needed for --chown to work
    #         - https://lists.samba.org/archive/rsync/2013-October/028753.html
    #
    # remote path includes always a trailing slash,
    # by `parameter substitution`, e.g.: "${var%/}"/
    # stripping if present and readding to avoid doubles
    #
    # Settings:
    #
    # - WEBSITE_LOCAL_USER
    # - WEBSITE_LOCAL_GROUP
    # - WEBSITE_REMOTE_SERVER
    # - WEBSITE_ORIG_PATH
    # - WEBSITE_COPY_PATH
    #
    echo "copying files..."
    sudo \
        rsync -rlp --owner --group \
            --chown="$WEBSITE_LOCAL_USER:$WEBSITE_LOCAL_GROUP" \
            "$USER"@"$WEBSITE_REMOTE_SERVER":"${WEBSITE_ORIG_PATH%/}"/ \
            "$WEBSITE_COPY_PATH"
    check_exit $?
}

copy_files_local() {
    # copy files on local server using rsync
    # rsync opts
    # -a archive mode; equals -rlptgoD (no -H,-A,-X)
    # -u skip files that are newer on the receiver
    #
    # remote path includes always a trailing slash,
    # by `parameter substitution`, e.g.: "${var%/}"/
    # stripping if present and readding to avoid doubles
    #
    # Settings:
    #
    # - WEBSITE_ORIG_PATH
    # - WEBSITE_COPY_PATH
    #
    echo "copying files..."
    sudo \
        rsync -au \
            "${WEBSITE_ORIG_PATH%/}"/ \
            "$WEBSITE_COPY_PATH"
    check_exit $?
}

override_files() {
    # copying files from override directory
    #
    # Settings:
    #
    # - WEBSITE_LOCAL_USER
    # - OVERRIDE_PATH
    # - WEBSITE_COPY_PATH
    #
    echo "copying files from override directory..."
    sudo -u "$WEBSITE_LOCAL_USER" \
        cp -dpr "${OVERRIDE_PATH%/}"/. "$WEBSITE_COPY_PATH"
    check_exit $?
}

create_local_db() {
    # create new db on local instance
    #
    # ref: http://stackoverflow.com/questions/13357760/mysql-create-user-if-not-exists#
    #
    # Settings:
    #
    # - DB_COPY_NAME
    # - DB_COPY_USER
    # - DB_COPY_PASS
    #
    echo "creating local database..."
    mysql <<HERE
        CREATE DATABASE IF NOT EXISTS ${DB_COPY_NAME};
        GRANT ALL ON ${DB_COPY_NAME}.* TO ${DB_COPY_USER}@'localhost' IDENTIFIED BY '${DB_COPY_PASS}';
        FLUSH PRIVILEGES;
HERE
    check_exit $?
}

create_remote_db() {
    # create new db on remote instance
    #
    # ref: http://stackoverflow.com/questions/13357760/mysql-create-user-if-not-exists#
    #
    # Settings:
    #
    # - DB_SERVER
    # - DB_PRIV_USER
    # - DB_COPY_NAME
    # - DB_COPY_USER
    # - DB_COPY_ACCESS_HOST
    # - DB_COPY_PASS
    #
    echo "creating remote database..."
    mysql -h "$DB_SERVER" -u "$DB_PRIV_USER" -p <<HERE
        CREATE DATABASE IF NOT EXISTS ${DB_COPY_NAME};
        GRANT ALL ON ${DB_COPY_NAME}.* TO ${DB_COPY_USER}@'${DB_COPY_ACCESS_HOST}' IDENTIFIED BY '${DB_COPY_PASS}';
        FLUSH PRIVILEGES;
HERE
    check_exit $?
}

copy_database() {
    # copy database from remote to local (encrypted)
    # using ssh, mysqldump, mysql and gzip
    #
    # ref: http://tltech.com/info/mysql-via-ssh/
    #
    # Settings:
    #
    # - DB_SERVER
    # - DB_ORIG_NAME
    # - DB_COPY_NAME
    #
    echo "copying database from remote..."
    ssh "$DB_SERVER" "mysqldump $DB_ORIG_NAME | gzip -c" \
        | gzip -d | mysql "$DB_COPY_NAME"
    check_exit $?
}

copy_database_remote() {
    # copy database on remote server (not encrypted)
    # using mysqldump and mysql (creates a local dump, temporary)
    #
    # Settings:
    #
    # - DB_SERVER
    # - DB_PRIV_USER
    # - DB_ORIG_NAME
    # - DB_COPY_NAME
    #
    DB_TMPFILE="db-tmp.sql"
    echo "copying database on remote server..."
    # using pipe, doesn't work (?)
    #mysqldump -h "$DB_SERVER" -u "$DB_PRIV_USER" -p "$DB_ORIG_NAME" | \
    #mysql -h "$DB_SERVER" -u "$DB_PRIV_USER" -p "$DB_COPY_NAME"
    echo "dumping..."
    mysqldump -h "$DB_SERVER" -u "$DB_PRIV_USER" -p "$DB_ORIG_NAME" > "$DB_TMPFILE"
    echo "inserting..."
    mysql -h "$DB_SERVER" -u "$DB_PRIV_USER" -p "$DB_COPY_NAME" < "$DB_TMPFILE"
    rm db-tmp.sql
    check_exit $?
}

edit_joomla_config() {
    # auto-magically edit joomla config
    # using sed
    #
    # e.g.:
    # sed "s/\$user = '[^']*'/\$user = \'$loon\'/" configuration.php
    # or:
    # sed "/\$user = /s/'[^']*'/'$loon'/" configuration.php
    #
    # evtl. use sed -e instead of single calls
    #
    # Settings:
    #
    # - WEBSITE_COPY_PATH
    # - DB_SERVER
    # - DB_COPY_NAME
    # - DB_COPY_USER
    # - DB_COPY_PASS
    #
    echo "auto-edit joomla config..."
    sudo sed -i_$(date +%Y-%m-%d.production_orig) "/\$host = /s/'[^']*'/'$DB_SERVER'/" "${WEBSITE_COPY_PATH%/}"/configuration.php
    sudo sed -i "/\$user = /s/'[^']*'/'$DB_COPY_USER'/" "${WEBSITE_COPY_PATH%/}"/configuration.php
    sudo sed -i "/\$password = /s/'[^']*'/'$DB_COPY_PASS'/" "${WEBSITE_COPY_PATH%/}"/configuration.php
    sudo sed -i "/\$db = /s/'[^']*'/'$DB_COPY_NAME'/" "${WEBSITE_COPY_PATH%/}"/configuration.php
    sudo sed -i \
        "s!\$log_path = '[^']*'!\$log_path = '${WEBSITE_COPY_PATH%/}/logs'!" \
        "${WEBSITE_COPY_PATH%/}"/configuration.php
    sudo sed -i \
        "s!\$tmp_path = '[^']*'!\$tmp_path = '${WEBSITE_COPY_PATH%/}/tmp'!" \
        "${WEBSITE_COPY_PATH%/}"/configuration.php
}
