#!/bin/bash
#
#
# module -l-l-rdb-rdb
#
# website local-to-local
# database remote-to-remote
#
# expected config options
#
# - COPY_FILES
# - WEBSITE_ORIG_PATH
# - WEBSITE_COPY_PATH
#
# for override files:
# - WEBSITE_LOCAL_USER
# - OVERRIDE_PATH
#
# for copy database:
# - DB_SERVER
# - DB_USER
# - DB_COPY_NAME
# - DB_COPY_USER
# - DB_ACCESS_HOST

. functions

check_args "$@"

if $COPY_FILES; then
    copy_files_local
fi

if $OVERRIDE_FILES; then
    override_files
fi

if $COPY_DB; then
    create_remote_db
    copy_database_remote
fi

if $AUTO_EDIT_JOOMLA_CONFIG; then
    edit_joomla_config
fi

echo "finished!"
