#!/bin/bash
#
# modular script to copy websites
#
# module -r-l-rdb-ldb
#
# website remote-to-local
# database remote-to-local
#

. functions

check_args "$@"

if $COPY_FILES; then
    copy_files
fi

if $OVERRIDE_FILES; then
    override_files
fi

if $COPY_DB; then
    create_local_db
    copy_database
fi

if $AUTO_EDIT_JOOMLA_CONFIG; then
    DB_SERVER="localhost"
    edit_joomla_config
fi

echo "finished!"
