#!/bin/bash
#
# modular script to copy websites
#
# module template
# create a copy and adapt for respective use case
#
# e.g.
# website local-to-local
# database remote-to-remote
#

. functions

check_args "$@"

# insert functions below
# e.g.

#if $COPY_FILES; then
#    copy_files_local
#fi

#if $OVERRIDE_FILES; then
#    override_files
#fi

#if $COPY_DB; then
#    create_remote_db
#    copy_database_remote
#fi

#if $AUTO_EDIT_JOOMLA_CONFIG; then
#    edit_joomla_config
#fi

echo "finished!"
