#!/bin/bash
#
# modular script to copy websites
#
# module -l-l-rdb-rdb
#
# website local-to-local
# database remote-to-remote
#

. functions

check_args "$@"

if $COPY_FILES; then
    copy_files_local
fi

if $OVERRIDE_FILES; then
    override_files
fi

if $COPY_DB; then
    create_remote_db
    copy_database_remote
fi

if $AUTO_EDIT_JOOMLA_CONFIG; then
    edit_joomla_config
fi

echo "finished!"
